services:
  sms-v2:
    build: .
    container_name: sms-v2
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production

