name: Deploy sms-activate

on:
  push:
    paths:
      - "sms-activate/**"
      - ".github/workflows/deploy-sms-activate.yml"
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: SSH into VPS and deploy sms-activate
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/client_28482_4/ZERKER/sms-activate
            git pull
            npm install --omit=dev
            pm2 restart sms-activate || pm2 start index.js --name sms-activate

