name: Deploy root-index

on:
  push:
    branches: [main]
    paths:
      - 'root-index/**'
      - '.github/workflows/deploy-root-index.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy root-index
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} <<'EOF'
          set -euo pipefail
          cd /srv/app/repo
          git pull origin main
          cd root-index
          npm ci --omit=dev
          pm2 restart root-index || pm2 start index.js --name root-index
          EOF
