name: Deploy tech-god-bug

on:
  push:
    branches: [main]
    paths:
      - 'tech-god-bug/**'
      - '.github/workflows/deploy-tech-god-bug.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy tech-god-bug
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
          cd /srv/app/repo/tech-god-bug || exit 1
          git pull origin main
          pm2 stop tech-bot || true
          npm install
          pm2 restart tech-bot || pm2 start index.js --name tech-bot
          EOF
