name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat <<EOF >> ~/.ssh/config
          Host vps
            HostName ${{ secrets.VPS_HOST }}
            User ${{ secrets.VPS_USER }}
            StrictHostKeyChecking no
          EOF

      - name: Deploy projects
        run: |
          ssh vps << 'EOF'
          # === sms-activate ===
          cd /home/client_28482_4/scripts/sms-activate
          if [ -d .git ]; then
            git pull origin main
          else
            git clone https://github.com/zerken11/ZERKER.git .
          fi
          npm ci --production || npm install --production

          # === tech-god-bug ===
          cd /home/client_28482_4/TECH-GOD-BUG-BOT
          if [ -d .git ]; then
            git pull origin main
          else
            git clone https://github.com/zerken11/ZERKER.git .
          fi
          npm ci --production || npm install --production

          # === root-index ===
          cd /home/client_28482_4
          [ -f package.json ] && (npm ci --production || npm install --production)

          # Restart all apps via PM2 ecosystem
          pm2 start /home/client_28482_4/ecosystem.config.js
          pm2 save
          EOF
