name: Deploy tech-god-bug

on:
  push:
    branches: [main]
    paths:
      - 'tech-god-bug/**'
      - '.github/workflows/deploy-tech-god-bug.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy tech-god-bug
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} <<'EOF'
          set -euo pipefail
          cd /srv/app/repo
          git pull origin main
          cd tech-god-bug
          npm ci --omit=dev
          pm2 restart tech-god-bug || pm2 start main.js --name tech-god-bug
          EOF
