name: Fixer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        run: npm install

      - name: Lint code with ESLint
        run: npx eslint . || true

      - name: Format code with Prettier
        run: npx prettier --check . || true

